---
namespace: serverscom
name: mitogen
version: 1.4.0
readme: README.md
authors:
  - Sergey Putko <psvmcc+ansible-galaxy@gmail.com>
  - George Shuklin <george.shuklin@gmail.com>
description: Mitogen strategy as collection
license:
  - MIT
tags: [ansible, mitogen]
dependencies: {}
repository: https://github.com/serverscom/ansible-collection-mitogen
documentation: https://github.com/serverscom/ansible-collection-mitogen
homepage: https://github.com/serverscom/ansible-collection-mitogen
issues: https://github.com/serverscom/ansible-collection-mitogen
